-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgziJ/DYyCkPHlGST5
JTNV/Ohfw1BhGlfY3mN0/WUO1QmgCgYIKoZIzj0DAQehRANCAAQyG+bv70umjqfT
tSiGd3VaBJRkszohSOcyxjumyScTGdSLJYkylT8f3FQA4erCtg4zgQwXDhAsq0KT
buV0SgE7
-----END PRIVATE KEY-----